name: Dispatch Update

on:
  repository_dispatch:
    types: [update-printing-proto]
  workflow_dispatch:
    inputs:
      reason:
        description: マニュアル操作で実行する理由
        required: false
        type: string

jobs:
  print_proto_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Remove existing yoshidax_example_proto directory
      run: |
        rm -rf yoshidax_example_proto

    - name: Clone yoshidax_example_proto repository
      env:
        PRIVATE_GH_PAT: ${{ secrets.PRIVATE_GH_PAT }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone https://yoshidax:${{ secrets.PRIVATE_GH_PAT }}@github.com/yoshidax/yoshidax_example_proto.git
        cd yoshidax_example_proto
        git checkout master
        git pull origin master
        rm -rf .git
        cd ..
        git add .
        git commit -m "Update proto files"
        git remote -v
        git push origin master